# Generated by Django 5.2.1 on 2025-05-26 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(max_length=50)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('url_video', models.URLField(blank=True, max_length=500, null=True)),
                ('url_imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('orden', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('respuesta_correcta', models.TextField(blank=True, null=True)),
                ('puntos', models.IntegerField(default=10)),
                ('tipo_actividad', models.CharField(choices=[('pregunta_respuesta', 'Pregunta y Respuesta'), ('seleccion_multiple', 'Selección Múltiple'), ('completar_espacios', 'Completar Espacios')], default='pregunta_respuesta', max_length=50)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('curso', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='leccion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.modulo'),
        ),
        migrations.AlterUniqueTogether(
            name='leccion',
            unique_together={('modulo', 'orden')},
        ),
        migrations.CreateModel(
            name='ProgresoActividad',
            fields=[
                ('id_progreso_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_intento', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoCurso',
            fields=[
                ('id_progreso_curso', models.AutoField(primary_key=True, serialize=False)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id_progreso_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'leccion')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoModulo',
            fields=[
                ('id_progreso_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
