# Generated by Django 5.2.1 on 2025-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresoactividad',
            name='puntos_otorgados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='puntos_otorgados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresoleccion',
            name='puntos_otorgados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresomodulo',
            name='puntos_otorgados',
            field=models.BooleanField(default=False),
        ),
    ]
