# Generated by Django 5.2.1 on 2025-05-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['orden']},
        ),
        migrations.AlterUniqueTogether(
            name='progresousuario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='puntos',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='progresousuario',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.actividad'),
        ),
        migrations.AddField(
            model_name='progresousuario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='progresousuario',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo'),
        ),
        migrations.AddField(
            model_name='progresousuario',
            name='puntos_ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.leccion'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='respuesta_correcta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.modulo'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='progresousuario',
            name='leccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.leccion'),
        ),
        migrations.AlterUniqueTogether(
            name='leccion',
            unique_together={('modulo', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together={('curso', 'orden')},
        ),
        migrations.RemoveField(
            model_name='progresousuario',
            name='puntaje_leccion',
        ),
    ]
