# Generated by Django 5.2.1 on 2025-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_progresoactividad_puntos_otorgados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text="Nombre de la categoría (ej. 'Lenguaje de Señas Básico')", max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría.', null=True)),
                ('slug', models.SlugField(help_text='Identificador amigable para URLs (se genera automáticamente).', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Curso',
                'verbose_name_plural': 'Categorías de Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorías a las que pertenece este curso.', related_name='cursos', to='cursos.categoriacurso'),
        ),
    ]
