# Generated by Django 5.2.1 on 2025-06-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puntos_experiencia',
        ),
    ]
