# Generated by Django 5.2.1 on 2025-06-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfilusuario_puntos_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_decir', 'Prefiero no decir')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='idioma_preferido',
            field=models.CharField(choices=[('es-co', 'Español (Colombia)'), ('en', 'English'), ('es', 'Español (General)')], default='es-co', max_length=7),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preferenciasaccesibilidad',
            name='contraste_alto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferenciasaccesibilidad',
            name='tamano_fuente',
            field=models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=50),
        ),
    ]
