# Generated by Django 5.2.1 on 2025-06-03 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_preferenciasaccesibilidad_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciasaccesibilidad',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_accesibilidad_usuario_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
