# Generated by Django 5.2.1 on 2025-06-03 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0003_categoriacurso_curso_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaContenidoAccesible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_audio_descripcion', models.BooleanField(default=False, help_text='Indica si el contenido tiene una descripción de audio para personas con discapacidad visual.')),
                ('tiene_subtitulos_lsc', models.BooleanField(default=False, help_text='Indica si el video o contenido tiene subtítulos en Lengua de Señas Colombiana.')),
                ('tiene_transcripcion_texto', models.BooleanField(default=False, help_text='Indica si el contenido tiene una transcripción de texto completa.')),
                ('es_compatible_lector_pantalla', models.BooleanField(default=False, help_text='Indica si el contenido está optimizado para lectores de pantalla.')),
                ('fecha_ultima_revision', models.DateTimeField(auto_now=True, help_text='Fecha de la última revisión de las características de accesibilidad.')),
                ('leccion', models.OneToOneField(help_text='Lección a la que se aplican estas características de accesibilidad.', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_accesibilidad', to='cursos.leccion')),
            ],
            options={
                'verbose_name': 'Característica de Contenido Accesible',
                'verbose_name_plural': 'Características de Contenido Accesible',
                'ordering': ['leccion__titulo'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuarioAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia_lsc', models.BooleanField(default=False, help_text='El usuario prefiere contenido con Lengua de Señas Colombiana.')),
                ('preferencia_audio_descripcion', models.BooleanField(default=False, help_text='El usuario prefiere contenido con descripciones de audio.')),
                ('preferencia_transcripcion_texto', models.BooleanField(default=False, help_text='El usuario prefiere contenido con transcripciones de texto.')),
                ('tamano_fuente', models.CharField(choices=[('pequeno', 'Pequeño'), ('normal', 'Normal'), ('grande', 'Grande'), ('extragrande', 'Extra Grande')], default='normal', help_text='Tamaño de fuente preferido por el usuario.', max_length=20)),
                ('contraste_alto', models.BooleanField(default=False, help_text='El usuario prefiere un esquema de colores de alto contraste.')),
                ('habilitar_reconocimiento_senas', models.BooleanField(default=False, help_text='El usuario desea usar el reconocimiento de señas a través de la cámara para actividades o traducciones.')),
                ('idioma_senas_preferido', models.CharField(choices=[('LSC', 'Lengua de Señas Colombiana'), ('ASL', 'American Sign Language'), ('LSE', 'Lengua de Signos Española')], default='LSC', help_text='Idioma de señas preferido por el usuario.', max_length=10)),
                ('usuario', models.OneToOneField(help_text='Usuario al que pertenecen estas preferencias de accesibilidad.', on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_accesibilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario de Accesibilidad',
                'verbose_name_plural': 'Preferencias de Usuario de Accesibilidad',
            },
        ),
    ]
