# Generated by Django 5.2.1 on 2025-05-27 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='insignias/')),
                ('puntos_requeridos', models.IntegerField(default=0, help_text='Puntos necesarios para obtener esta insignia (si aplica)')),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
            },
        ),
        migrations.CreateModel(
            name='PuntosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_gamificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntos de Usuario',
                'verbose_name_plural': 'Puntos de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(default=django.utils.timezone.now)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_con_insignia', to='gamificacion.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias_obtenidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insignia de Usuario',
                'verbose_name_plural': 'Insignias de Usuarios',
                'unique_together': {('usuario', 'insignia')},
            },
        ),
    ]
