# Generated by Django 5.2.1 on 2025-05-28 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0002_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosusuario',
            name='nivel_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_en_nivel', to='gamificacion.nivel'),
        ),
    ]
