# Generated by Django 5.2.1 on 2025-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0003_puntosusuario_nivel_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosusuario',
            name='last_daily_reward_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
