# Generated by Django 5.2.1 on 2025-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0004_puntosusuario_last_daily_reward_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='insignia',
            name='tipo_desbloqueo',
            field=models.CharField(choices=[('puntos', 'Por Puntos Totales'), ('accion', 'Por Acción Específica'), ('complejidad', 'Por Criterio Complejo')], default='accion', help_text='Define cómo se desbloquea esta insignia', max_length=50),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='puntos_requeridos',
            field=models.IntegerField(default=0, help_text='Puntos necesarios para obtener esta insignia (solo si "Por Puntos Totales")'),
        ),
    ]
