# Generated by Django 5.2.1 on 2025-06-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0005_insignia_tipo_desbloqueo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntosusuario',
            old_name='last_daily_reward_date',
            new_name='last_daily_login_award',
        ),
        migrations.AddField(
            model_name='puntosusuario',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
